apiVersion: v1
kind: Service
metadata:
  name: doodleshareex
spec:
  selector:
    app: doodleshareex
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doodleshareex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doodleshareex
  template:
    metadata:
      labels:
        app: doodleshareex
    spec:
      containers:
      - name: doodleshareex
        image: dotnsf/doodleshareex
        env:
        - name: REDIS_SERVER
          value: "159.122.175.21"
        - name: REDIS_PORT
          value: "30379"
        - name: USEDB
          value: "cloudant_old"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "P@ssw0rd"
        - name: DB_NAME
          value: "mydb"
        - name: DB_URL
          value: "http://159.122.175.21:30984/"
        ports:
        - containerPort: 8080
