apiVersion: apps/v1
kind: Deployment
metadata:
  name: doodleshareex-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doodleshareex-client
  template:
    metadata:
      labels:
        app: doodleshareex-client
    spec:
      containers:
      - name: doodleshareex-client
        image: dotnsf/doodleshareex-client
        env:
        - name: UUID
          value: "user0"
        - name: ROOM
          value: "dotnsf"
        - name: IMAGES_FOLDER
          value: "sample_images/he"
        - name: INTERVAL_MS
          value: "3000"
        - name: SERVER_URL
          value: "wss://doodleshareex.yellowmix.net"
