apiVersion: v1
kind: Service
metadata:
  name: postgresserver
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30432
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        env:
        - name: POSTGRES_PASSWORD
          value: "Passw0rd"
        - name: POSTGRES_DB
          value: "mydb"
        - name: POSTGRES_USER
          value: "admin"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
spec:
  selector:
    app: pgadmin4
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@testtest.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 80
